// ===== こくご：かんじクイズ =====
// kanji: 漢字, reading: 出題する読み方(ひらがな), word: その読み方を含む熟語・例（3年以上は穴埋めで□に置き換えて表示する。用例は、その学年までに習う漢字だけで作る）

const KANJI_DATA = {
  2: [
    { kanji: '引', reading: 'ひ', word: '引く' },
    { kanji: '園', reading: 'えん', word: '公園' },
    { kanji: '遠', reading: 'とお', word: '遠い' },
    { kanji: '夏', reading: 'なつ', word: '夏休み' },
    { kanji: '家', reading: 'いえ', word: '家の中' },
    { kanji: '歌', reading: 'うた', word: '歌う' },
    { kanji: '回', reading: 'まわ', word: '回る' },
    { kanji: '会', reading: 'あ', word: '会う' },
    { kanji: '海', reading: 'うみ', word: '海の水' },
    { kanji: '絵', reading: 'え', word: '絵本' },
    { kanji: '外', reading: 'がい', word: '外国' },
    { kanji: '楽', reading: 'たの', word: '楽しい' },
    { kanji: '間', reading: 'かん', word: '時間' },
    { kanji: '顔', reading: 'かお', word: '顔色' },
    { kanji: '汽', reading: 'き', word: '汽車' },
    { kanji: '記', reading: 'き', word: '日記' },
    { kanji: '帰', reading: 'かえ', word: '帰る' },
    { kanji: '魚', reading: 'さかな', word: '魚つり' },
    { kanji: '京', reading: 'きょう', word: '東京' },
    { kanji: '強', reading: 'つよ', word: '強い' },
    { kanji: '教', reading: 'おし', word: '教える' },
    { kanji: '近', reading: 'ちか', word: '近い' },
    { kanji: '兄', reading: 'にい', word: 'お兄さん' },
    { kanji: '計', reading: 'けい', word: '時計' },
    { kanji: '言', reading: 'い', word: '言う' },
    { kanji: '原', reading: 'はら', word: '原っぱ' },
    { kanji: '古', reading: 'ふる', word: '古い' },
    { kanji: '午', reading: 'ご', word: '午前' },
    { kanji: '後', reading: 'うし', word: '後ろ' },
    { kanji: '語', reading: 'ご', word: '国語' },
    { kanji: '工', reading: 'こう', word: '工場' },
    { kanji: '公', reading: 'こう', word: '公園' },
    { kanji: '広', reading: 'ひろ', word: '広い' },
    { kanji: '交', reading: 'こう', word: '交番' },
    { kanji: '光', reading: 'こう', word: '日光' },
    { kanji: '考', reading: 'かんが', word: '考える' },
    { kanji: '行', reading: 'い', word: '行く' },
    { kanji: '高', reading: 'たか', word: '高い' },
    { kanji: '黄', reading: 'き', word: '黄色' },
    { kanji: '合', reading: 'あ', word: '合う' },
    { kanji: '黒', reading: 'くろ', word: '黒い' },
    { kanji: '今', reading: 'いま', word: '今ごろ' },
    { kanji: '細', reading: 'ほそ', word: '細い' },
    { kanji: '作', reading: 'つく', word: '作る' },
    { kanji: '算', reading: 'さん', word: '算数' },
    { kanji: '止', reading: 'と', word: '止まる' },
    { kanji: '姉', reading: 'ねえ', word: 'お姉さん' },
    { kanji: '思', reading: 'おも', word: '思う' },
    { kanji: '紙', reading: 'かみ', word: '紙ひこうき' },
    { kanji: '寺', reading: 'てら', word: 'お寺' },
    { kanji: '自', reading: 'じ', word: '自分' },
    { kanji: '室', reading: 'しつ', word: '教室' },
    { kanji: '社', reading: 'しゃ', word: '会社' },
    { kanji: '弱', reading: 'よわ', word: '弱い' },
    { kanji: '首', reading: 'くび', word: '手首' },
    { kanji: '秋', reading: 'あき', word: '秋風' },
    { kanji: '週', reading: 'しゅう', word: '毎週' },
    { kanji: '春', reading: 'はる', word: '春休み' },
    { kanji: '書', reading: 'か', word: '書く' },
    { kanji: '少', reading: 'すく', word: '少ない' },
    { kanji: '場', reading: 'じょう', word: '工場' },
    { kanji: '食', reading: 'た', word: '食べる' },
    { kanji: '新', reading: 'あたら', word: '新しい' },
    { kanji: '親', reading: 'おや', word: '親子' },
    { kanji: '数', reading: 'すう', word: '数字' },
    { kanji: '西', reading: 'にし', word: '西口' },
    { kanji: '声', reading: 'せい', word: '音声' },
    { kanji: '星', reading: 'ほし', word: '星空' },
    { kanji: '晴', reading: 'は', word: '晴れる' },
    { kanji: '切', reading: 'き', word: '切る' },
    { kanji: '雪', reading: 'ゆき', word: '大雪' },
    { kanji: '線', reading: 'せん', word: '直線' },
    { kanji: '前', reading: 'まえ', word: '名前' },
    { kanji: '走', reading: 'はし', word: '走る' },
    { kanji: '多', reading: 'おお', word: '多い' },
    { kanji: '台', reading: 'たい', word: '台風' },
    { kanji: '池', reading: 'いけ', word: '池の水' },
    { kanji: '知', reading: 'し', word: '知る' },
    { kanji: '茶', reading: 'ちゃ', word: 'お茶' },
    { kanji: '昼', reading: 'ひる', word: '昼休み' },
    { kanji: '長', reading: 'なが', word: '長い' },
    { kanji: '鳥', reading: 'とり', word: '小鳥' },
    { kanji: '朝', reading: 'あさ', word: '朝日' },
    { kanji: '直', reading: 'なお', word: '直す' },
    { kanji: '通', reading: 'とお', word: '通る' },
    { kanji: '弟', reading: 'だい', word: '兄弟' },
    { kanji: '店', reading: 'みせ', word: 'お店' },
    { kanji: '点', reading: 'てん', word: '百点' },
    { kanji: '電', reading: 'でん', word: '電車' },
    { kanji: '冬', reading: 'ふゆ', word: '冬休み' },
    { kanji: '当', reading: 'あ', word: '当たる' },
    { kanji: '東', reading: 'ひがし', word: '東口' },
    { kanji: '答', reading: 'こた', word: '答える' },
    { kanji: '頭', reading: 'あたま', word: '頭の上' },
    { kanji: '同', reading: 'おな', word: '同じ' },
    { kanji: '道', reading: 'みち', word: '道草' },
    { kanji: '読', reading: 'よ', word: '読む' },
    { kanji: '内', reading: 'うち', word: '内がわ' },
    { kanji: '南', reading: 'みなみ', word: '南口' },
    { kanji: '肉', reading: 'にく', word: '牛肉' },
    { kanji: '馬', reading: 'うま', word: '子馬' },
    { kanji: '売', reading: 'う', word: '売る' },
    { kanji: '買', reading: 'か', word: '買う' },
    { kanji: '麦', reading: 'むぎ', word: '麦茶' },
    { kanji: '半', reading: 'はん', word: '半分' },
    { kanji: '番', reading: 'ばん', word: '一番' },
    { kanji: '父', reading: 'とう', word: 'お父さん' },
    { kanji: '風', reading: 'かぜ', word: '北風' },
    { kanji: '分', reading: 'わ', word: '分かる' },
    { kanji: '聞', reading: 'き', word: '聞く' },
    { kanji: '米', reading: 'こめ', word: '米つぶ' },
    { kanji: '歩', reading: 'ある', word: '歩く' },
    { kanji: '母', reading: 'かあ', word: 'お母さん' },
    { kanji: '方', reading: 'ほう', word: '東の方' },
    { kanji: '北', reading: 'きた', word: '北口' },
    { kanji: '毎', reading: 'まい', word: '毎日' },
    { kanji: '妹', reading: 'まい', word: '姉妹' },
    { kanji: '万', reading: 'まん', word: '一万' },
    { kanji: '明', reading: 'あか', word: '明るい' },
    { kanji: '鳴', reading: 'な', word: '鳴く' },
    { kanji: '毛', reading: 'け', word: '毛糸' },
    { kanji: '門', reading: 'もん', word: '校門' },
    { kanji: '夜', reading: 'や', word: '今夜' },
    { kanji: '野', reading: 'の', word: '野原' },
    { kanji: '友', reading: 'とも', word: '友だち' },
    { kanji: '曜', reading: 'よう', word: '日曜日' },
    { kanji: '来', reading: 'く', word: '来る' },
    { kanji: '理', reading: 'り', word: '地理' },
    { kanji: '話', reading: 'はな', word: '話す' },
    { kanji: '何', reading: 'なん', word: '何時' },
    { kanji: '科', reading: 'か', word: '理科' },
    { kanji: '角', reading: 'かく', word: '三角' },
    { kanji: '丸', reading: 'まる', word: '丸い' },
    { kanji: '岩', reading: 'いわ', word: '岩山' },
    { kanji: '弓', reading: 'ゆみ', word: '弓矢' },
    { kanji: '元', reading: 'げん', word: '元気' },
    { kanji: '活', reading: 'かつ', word: '生活' }
  ],
  4: [
    { kanji: '愛', reading: 'あい', word: '愛犬' },
    { kanji: '案', reading: 'あん', word: '案内' },
    { kanji: '以', reading: 'い', word: '以上' },
    { kanji: '位', reading: 'い', word: '順位' },
    { kanji: '印', reading: 'いん', word: '印刷' },
    { kanji: '英', reading: 'えい', word: '英語' },
    { kanji: '塩', reading: 'しお', word: '塩水' },
    { kanji: '億', reading: 'おく', word: '一億' },
    { kanji: '加', reading: 'くわ', word: '加える' },
    { kanji: '果', reading: 'か', word: '果実' },
    { kanji: '改', reading: 'あらた', word: '改める' },
    { kanji: '械', reading: 'かい', word: '機械' },
    { kanji: '害', reading: 'がい', word: '水害' },
    { kanji: '街', reading: 'がい', word: '商店街' },
    { kanji: '各', reading: 'かく', word: '各自' },
    { kanji: '覚', reading: 'おぼ', word: '覚える' },
    { kanji: '完', reading: 'かん', word: '完全' },
    { kanji: '管', reading: 'かん', word: '水道管' },
    { kanji: '関', reading: 'かん', word: '関係' },
    { kanji: '観', reading: 'かん', word: '観光' },
    { kanji: '願', reading: 'ねが', word: '願う' },
    { kanji: '季', reading: 'き', word: '季節' },
    { kanji: '旗', reading: 'はた', word: '白旗' },
    { kanji: '器', reading: 'き', word: '楽器' },
    { kanji: '機', reading: 'き', word: '飛行機' },
    { kanji: '議', reading: 'ぎ', word: '会議' },
    { kanji: '求', reading: 'もと', word: '求める' },
    { kanji: '泣', reading: 'な', word: '泣く' },
    { kanji: '給', reading: 'きゅう', word: '給食' },
    { kanji: '漁', reading: 'りょう', word: '大漁' },
    { kanji: '共', reading: 'きょう', word: '共通' },
    { kanji: '協', reading: 'きょう', word: '協力' },
    { kanji: '鏡', reading: 'かがみ', word: '手鏡' },
    { kanji: '競', reading: 'きょう', word: '競走' },
    { kanji: '極', reading: 'きょく', word: '北極' },
    { kanji: '訓', reading: 'くん', word: '訓読み' },
    { kanji: '景', reading: 'けい', word: '風景' },
    { kanji: '芸', reading: 'げい', word: '手芸' },
    { kanji: '欠', reading: 'か', word: '欠ける' },
    { kanji: '結', reading: 'むす', word: '結ぶ' },
    { kanji: '建', reading: 'た', word: '建てる' },
    { kanji: '健', reading: 'けん', word: '健康' },
    { kanji: '験', reading: 'けん', word: '試験' },
    { kanji: '固', reading: 'かた', word: '固い' },
    { kanji: '功', reading: 'こう', word: '成功' },
    { kanji: '好', reading: 'す', word: '好き' },
    { kanji: '候', reading: 'こう', word: '天候' },
    { kanji: '菜', reading: 'さい', word: '野菜' },
    { kanji: '最', reading: 'さい', word: '最後' },
    { kanji: '材', reading: 'ざい', word: '木材' },
    { kanji: '昨', reading: 'さく', word: '昨年' },
    { kanji: '札', reading: 'さつ', word: '千円札' },
    { kanji: '刷', reading: 'さつ', word: '印刷' },
    { kanji: '察', reading: 'さつ', word: '観察' },
    { kanji: '参', reading: 'さん', word: '参加' },
    { kanji: '産', reading: 'さん', word: '産地' },
    { kanji: '散', reading: 'ち', word: '散る' },
    { kanji: '残', reading: 'のこ', word: '残る' },
    { kanji: '氏', reading: 'し', word: '氏名' },
    { kanji: '司', reading: 'し', word: '司会' },
    { kanji: '試', reading: 'し', word: '試合' },
    { kanji: '児', reading: 'じ', word: '児童' },
    { kanji: '辞', reading: 'じ', word: '辞書' },
    { kanji: '失', reading: 'うしな', word: '失う' },
    { kanji: '借', reading: 'か', word: '借りる' },
    { kanji: '種', reading: 'たね', word: '花の種' },
    { kanji: '周', reading: 'まわ', word: '周り' },
    { kanji: '祝', reading: 'いわ', word: '祝う' },
    { kanji: '順', reading: 'じゅん', word: '順番' },
    { kanji: '初', reading: 'はじ', word: '初めて' },
    { kanji: '松', reading: 'まつ', word: '松葉' },
    { kanji: '笑', reading: 'わら', word: '笑う' },
    { kanji: '唱', reading: 'しょう', word: '合唱' },
    { kanji: '焼', reading: 'や', word: '焼く' },
    { kanji: '照', reading: 'て', word: '照らす' },
    { kanji: '信', reading: 'しん', word: '信じる' },
    { kanji: '成', reading: 'せい', word: '成長' },
    { kanji: '省', reading: 'はぶ', word: '省く' },
    { kanji: '清', reading: 'きよ', word: '清い' },
    { kanji: '静', reading: 'しず', word: '静か' },
    { kanji: '席', reading: 'せき', word: '出席' },
    { kanji: '積', reading: 'つ', word: '積む' },
    { kanji: '折', reading: 'お', word: '折る' },
    { kanji: '説', reading: 'せつ', word: '説明' },
    { kanji: '浅', reading: 'あさ', word: '浅い' },
    { kanji: '戦', reading: 'たたか', word: '戦う' },
    { kanji: '選', reading: 'えら', word: '選ぶ' },
    { kanji: '然', reading: 'ぜん', word: '自然' },
    { kanji: '争', reading: 'あらそ', word: '争う' },
    { kanji: '倉', reading: 'そう', word: '倉庫' },
    { kanji: '巣', reading: 'す', word: '巣箱' },
    { kanji: '束', reading: 'たば', word: '花束' },
    { kanji: '側', reading: 'がわ', word: '右側' },
    { kanji: '続', reading: 'つづ', word: '続く' },
    { kanji: '卒', reading: 'そつ', word: '卒業' },
    { kanji: '帯', reading: 'たい', word: '熱帯' },
    { kanji: '単', reading: 'たん', word: '単語' },
    { kanji: '置', reading: 'お', word: '置く' },
    { kanji: '仲', reading: 'なか', word: '仲間' },
    { kanji: '兆', reading: 'ちょう', word: '一兆' },
    { kanji: '低', reading: 'ひく', word: '低い' },
    { kanji: '底', reading: 'てい', word: '海底' },
    { kanji: '的', reading: 'てき', word: '目的' },
    { kanji: '典', reading: 'てん', word: '辞典' },
    { kanji: '伝', reading: 'つた', word: '伝える' },
    { kanji: '徒', reading: 'と', word: '生徒' },
    { kanji: '努', reading: 'つと', word: '努める' },
    { kanji: '働', reading: 'はたら', word: '働く' },
    { kanji: '特', reading: 'とく', word: '特別' },
    { kanji: '念', reading: 'ねん', word: '記念' },
    { kanji: '梅', reading: 'うめ', word: '梅の花' },
    { kanji: '飯', reading: 'はん', word: 'ご飯' },
    { kanji: '飛', reading: 'と', word: '飛ぶ' }
  ],
  6: [
    { kanji: '異', reading: 'い', word: '異常' },
    { kanji: '域', reading: 'いき', word: '地域' },
    { kanji: '宇', reading: 'う', word: '宇宙' },
    { kanji: '映', reading: 'えい', word: '映画' },
    { kanji: '延', reading: 'の', word: '延びる' },
    { kanji: '沿', reading: 'そ', word: '沿う' },
    { kanji: '我', reading: 'わ', word: '我が家' },
    { kanji: '拡', reading: 'かく', word: '拡大' },
    { kanji: '割', reading: 'わ', word: '割る' },
    { kanji: '干', reading: 'ほ', word: '干す' },
    { kanji: '巻', reading: 'ま', word: '巻く' },
    { kanji: '看', reading: 'かん', word: '看板' },
    { kanji: '簡', reading: 'かん', word: '簡単' },
    { kanji: '危', reading: 'あぶ', word: '危ない' },
    { kanji: '机', reading: 'つくえ', word: '机の上' },
    { kanji: '吸', reading: 'す', word: '吸う' },
    { kanji: '供', reading: 'そな', word: '供える' },
    { kanji: '胸', reading: 'むね', word: '胸の中' },
    { kanji: '郷', reading: 'きょう', word: '故郷' },
    { kanji: '勤', reading: 'つと', word: '勤める' },
    { kanji: '筋', reading: 'きん', word: '筋肉' },
    { kanji: '系', reading: 'けい', word: '体系' },
    { kanji: '敬', reading: 'うやま', word: '敬う' },
    { kanji: '警', reading: 'けい', word: '警察' },
    { kanji: '劇', reading: 'げき', word: '演劇' },
    { kanji: '穴', reading: 'あな', word: '落とし穴' },
    { kanji: '権', reading: 'けん', word: '権利' },
    { kanji: '憲', reading: 'けん', word: '憲法' },
    { kanji: '源', reading: 'げん', word: '資源' },
    { kanji: '厳', reading: 'きび', word: '厳しい' },
    { kanji: '呼', reading: 'よ', word: '呼ぶ' },
    { kanji: '誤', reading: 'あやま', word: '誤る' },
    { kanji: '孝', reading: 'こう', word: '親孝行' },
    { kanji: '皇', reading: 'こう', word: '皇居' },
    { kanji: '紅', reading: 'こう', word: '紅白' },
    { kanji: '降', reading: 'ふ', word: '降る' },
    { kanji: '刻', reading: 'きざ', word: '刻む' },
    { kanji: '穀', reading: 'こく', word: '穀物' },
    { kanji: '骨', reading: 'ほね', word: '骨組み' },
    { kanji: '困', reading: 'こま', word: '困る' },
    { kanji: '砂', reading: 'すな', word: '砂場' },
    { kanji: '座', reading: 'すわ', word: '座る' },
    { kanji: '済', reading: 'す', word: '済む' },
    { kanji: '裁', reading: 'さい', word: '裁判' },
    { kanji: '策', reading: 'さく', word: '対策' },
    { kanji: '冊', reading: 'さつ', word: '一冊' },
    { kanji: '至', reading: 'いた', word: '至る' },
    { kanji: '私', reading: 'し', word: '私立' },
    { kanji: '姿', reading: 'すがた', word: '後ろ姿' },
    { kanji: '視', reading: 'し', word: '視力' },
    { kanji: '詞', reading: 'し', word: '名詞' },
    { kanji: '誌', reading: 'し', word: '雑誌' },
    { kanji: '磁', reading: 'じ', word: '磁石' },
    { kanji: '射', reading: 'しゃ', word: '反射' },
    { kanji: '捨', reading: 'す', word: '捨てる' },
    { kanji: '若', reading: 'わか', word: '若い' },
    { kanji: '樹', reading: 'じゅ', word: '樹木' },
    { kanji: '収', reading: 'おさ', word: '収める' },
    { kanji: '宗', reading: 'しゅう', word: '宗教' },
    { kanji: '就', reading: 'つ', word: '就く' },
    { kanji: '衆', reading: 'しゅう', word: '観衆' },
    { kanji: '従', reading: 'したが', word: '従う' },
    { kanji: '縦', reading: 'たて', word: '縦書き' },
    { kanji: '縮', reading: 'ちぢ', word: '縮む' },
    { kanji: '熟', reading: 'じゅく', word: '熟語' },
    { kanji: '純', reading: 'じゅん', word: '単純' },
    { kanji: '処', reading: 'しょ', word: '処理' },
    { kanji: '署', reading: 'しょ', word: '警察署' },
    { kanji: '諸', reading: 'しょ', word: '諸国' },
    { kanji: '除', reading: 'のぞ', word: '除く' },
    { kanji: '承', reading: 'しょう', word: '承知' },
    { kanji: '将', reading: 'しょう', word: '将来' },
    { kanji: '傷', reading: 'きず', word: '傷口' },
    { kanji: '障', reading: 'しょう', word: '故障' },
    { kanji: '蒸', reading: 'む', word: '蒸す' },
    { kanji: '針', reading: 'はり', word: '針金' },
    { kanji: '垂', reading: 'た', word: '垂れる' },
    { kanji: '推', reading: 'すい', word: '推理' },
    { kanji: '盛', reading: 'さか', word: '盛ん' },
    { kanji: '誠', reading: 'せい', word: '誠実' },
    { kanji: '宣', reading: 'せん', word: '宣言' },
    { kanji: '専', reading: 'せん', word: '専門' },
    { kanji: '泉', reading: 'せん', word: '温泉' },
    { kanji: '洗', reading: 'あら', word: '洗う' },
    { kanji: '染', reading: 'そ', word: '染める' },
    { kanji: '善', reading: 'ぜん', word: '親善' },
    { kanji: '奏', reading: 'そう', word: '演奏' },
    { kanji: '創', reading: 'そう', word: '創作' },
    { kanji: '装', reading: 'そう', word: '服装' },
    { kanji: '層', reading: 'そう', word: '地層' },
    { kanji: '操', reading: 'そう', word: '体操' },
    { kanji: '蔵', reading: 'ぞう', word: '冷蔵庫' },
    { kanji: '臓', reading: 'ぞう', word: '内臓' },
    { kanji: '存', reading: 'そん', word: '存在' },
    { kanji: '尊', reading: 'とうと', word: '尊い' },
    { kanji: '宅', reading: 'たく', word: '住宅' },
    { kanji: '担', reading: 'たん', word: '担任' },
    { kanji: '探', reading: 'さが', word: '探す' },
    { kanji: '誕', reading: 'たん', word: '誕生' },
    { kanji: '段', reading: 'だん', word: '階段' },
    { kanji: '暖', reading: 'あたた', word: '暖かい' },
    { kanji: '値', reading: 'ね', word: '値段' },
    { kanji: '宙', reading: 'ちゅう', word: '宇宙' },
    { kanji: '忠', reading: 'ちゅう', word: '忠告' },
    { kanji: '著', reading: 'ちょ', word: '著者' },
    { kanji: '庁', reading: 'ちょう', word: '県庁' },
    { kanji: '頂', reading: 'ちょう', word: '山頂' },
    { kanji: '潮', reading: 'しお', word: '潮風' },
    { kanji: '賃', reading: 'ちん', word: '運賃' },
    { kanji: '痛', reading: 'いた', word: '痛い' },
    { kanji: '展', reading: 'てん', word: '展示' },
    { kanji: '討', reading: 'とう', word: '検討' },
    { kanji: '党', reading: 'とう', word: '政党' },
    { kanji: '糖', reading: 'とう', word: '砂糖' },
    { kanji: '届', reading: 'とど', word: '届ける' },
    { kanji: '難', reading: 'むずか', word: '難しい' },
    { kanji: '乳', reading: 'にゅう', word: '牛乳' },
    { kanji: '認', reading: 'みと', word: '認める' },
    { kanji: '脳', reading: 'のう', word: '頭脳' },
    { kanji: '派', reading: 'は', word: '派手' },
    { kanji: '背', reading: 'せ', word: '背中' },
    { kanji: '肺', reading: 'はい', word: '肺活量' },
    { kanji: '俳', reading: 'はい', word: '俳句' },
    { kanji: '班', reading: 'はん', word: '班長' },
    { kanji: '晩', reading: 'ばん', word: '今晩' },
    { kanji: '否', reading: 'ひ', word: '否定' },
    { kanji: '批', reading: 'ひ', word: '批判' },
    { kanji: '秘', reading: 'ひ', word: '秘密' },
    { kanji: '腹', reading: 'はら', word: '腹ぺこ' },
    { kanji: '奮', reading: 'ふん', word: '興奮' },
    { kanji: '並', reading: 'なら', word: '並ぶ' },
    { kanji: '閉', reading: 'し', word: '閉まる' },
    { kanji: '片', reading: 'かた', word: '片道' },
    { kanji: '補', reading: 'おぎな', word: '補う' },
    { kanji: '暮', reading: 'く', word: '暮らす' },
    { kanji: '宝', reading: 'たから', word: '宝物' },
    { kanji: '訪', reading: 'ほう', word: '訪問' },
    { kanji: '亡', reading: 'な', word: '亡くなる' },
    { kanji: '忘', reading: 'わす', word: '忘れる' },
    { kanji: '棒', reading: 'ぼう', word: '鉄棒' },
    { kanji: '枚', reading: 'まい', word: '一枚' },
    { kanji: '幕', reading: 'まく', word: '開幕' },
    { kanji: '密', reading: 'みつ', word: '密度' },
    { kanji: '盟', reading: 'めい', word: '同盟' },
    { kanji: '模', reading: 'も', word: '模様' },
    { kanji: '訳', reading: 'やく', word: '通訳' },
    { kanji: '郵', reading: 'ゆう', word: '郵便' },
    { kanji: '優', reading: 'やさ', word: '優しい' },
    { kanji: '幼', reading: 'おさな', word: '幼い' },
    { kanji: '欲', reading: 'ほ', word: '欲しい' },
    { kanji: '翌', reading: 'よく', word: '翌日' },
    { kanji: '乱', reading: 'みだ', word: '乱れる' },
    { kanji: '卵', reading: 'たまご', word: '生卵' },
    { kanji: '覧', reading: 'らん', word: '一覧' },
    { kanji: '裏', reading: 'うら', word: '裏口' },
    { kanji: '律', reading: 'りつ', word: '法律' },
    { kanji: '朗', reading: 'ろう', word: '朗読' },
    { kanji: '論', reading: 'ろん', word: '論文' }
  ],
  1: [
    // やさしい前半 1〜25（数・自然・元素・天気・植物・動物）
    // 1年生：yomi = 語の全体の読み。「yomi の reading を かんじで かくと？」と聞く（reading は必ず yomi の一部）。wordKana/word は参考データ。
    { kanji: '一', reading: 'いち',   word: '一日',   wordKana: '□にち',   yomi: 'いちにち' },
    { kanji: '二', reading: 'に',     word: '二月',   wordKana: '□がつ',   yomi: 'にがつ' },
    { kanji: '三', reading: 'さん',   word: '三角',   wordKana: '□かく',   yomi: 'さんかく' },
    { kanji: '四', reading: 'し',     word: '四角',   wordKana: '□かく',   yomi: 'しかく' },
    { kanji: '五', reading: 'ご',     word: '五人',   wordKana: '□にん',   yomi: 'ごにん' },
    { kanji: '六', reading: 'ろく',   word: '六年',   wordKana: '□ねん',   yomi: 'ろくねん' },
    { kanji: '七', reading: 'しち',   word: '七五三', wordKana: '□ごさん', yomi: 'しちごさん' },
    { kanji: '八', reading: 'はち',   word: '八月',   wordKana: '□がつ',   yomi: 'はちがつ' },
    { kanji: '九', reading: 'きゅう', word: '九本',   wordKana: '□ほん',   yomi: 'きゅうほん' },
    { kanji: '十', reading: 'じゅう', word: '十月',   wordKana: '□がつ',   yomi: 'じゅうがつ' },
    { kanji: '日', reading: 'ひ',     word: '日の出', wordKana: '□ので',   yomi: 'ひので' },
    { kanji: '月', reading: 'つき',   word: 'お月さま', wordKana: 'お□さま', yomi: 'おつきさま' },
    { kanji: '山', reading: 'やま',   word: '山道',   wordKana: '□みち',   yomi: 'やまみち' },
    { kanji: '川', reading: 'かわ',   word: '川岸',   wordKana: '□ぎし',   yomi: 'かわぎし' },
    { kanji: '田', reading: 'た',     word: '田んぼ', wordKana: '□んぼ',   yomi: 'たんぼ' },
    { kanji: '木', reading: 'き',     word: '木の枝', wordKana: '□のえだ', yomi: 'きのえだ' },
    { kanji: '水', reading: 'みず',   word: '水色',   wordKana: '□いろ',   yomi: 'みずいろ' },
    { kanji: '火', reading: 'ひ',     word: '火あそび', wordKana: '□あそび', yomi: 'ひあそび' },
    { kanji: '土', reading: 'つち',   word: '土いじり', wordKana: '□いじり', yomi: 'つちいじり' },
    { kanji: '花', reading: 'はな',   word: '花火',   wordKana: '□び',     yomi: 'はなび' },
    { kanji: '草', reading: 'くさ',   word: '草むら', wordKana: '□むら',   yomi: 'くさむら' },
    { kanji: '天', reading: 'てん',   word: '天気',   wordKana: '□き',     yomi: 'てんき' },
    { kanji: '雨', reading: 'あめ',   word: '大雨',   wordKana: 'おお□',   yomi: 'おおあめ' },
    { kanji: '空', reading: 'そら',   word: '空色',   wordKana: '□いろ',   yomi: 'そらいろ' },
    { kanji: '犬', reading: 'いぬ',   word: '子犬',   wordKana: 'こ□',     yomi: 'こいぬ' },
    // むずかしい後半 26〜50（からだ・方向・もの・学校・大きい数）
    { kanji: '人', reading: 'ひと',   word: '人ごみ', wordKana: '□ごみ',   yomi: 'ひとごみ' },
    { kanji: '口', reading: 'くち',   word: '口笛',   wordKana: '□ぶえ',   yomi: 'くちぶえ' },
    { kanji: '手', reading: 'て',     word: '手足',   wordKana: '□あし',   yomi: 'てあし' },
    { kanji: '目', reading: 'め',     word: '目玉',   wordKana: '□だま',   yomi: 'めだま' },
    { kanji: '耳', reading: 'みみ',   word: '右耳',   wordKana: 'みぎ□',   yomi: 'みぎみみ' },
    { kanji: '足', reading: 'あし',   word: '足音',   wordKana: '□おと',   yomi: 'あしおと' },
    { kanji: '上', reading: 'うえ',   word: '山の上', wordKana: 'やまの□', yomi: 'やまのうえ' },
    { kanji: '下', reading: 'した',   word: '木の下', wordKana: 'きの□',   yomi: 'きのした' },
    { kanji: '左', reading: 'ひだり', word: '左手',   wordKana: '□て',     yomi: 'ひだりて' },
    { kanji: '右', reading: 'みぎ',   word: '右手',   wordKana: '□て',     yomi: 'みぎて' },
    { kanji: '中', reading: 'なか',   word: '川の中', wordKana: 'かわの□', yomi: 'かわのなか' },
    { kanji: '大', reading: 'おお',   word: '大きい', wordKana: '□きい',   yomi: 'おおきい' },
    { kanji: '小', reading: 'ちい',   word: '小さい', wordKana: '□さい',   yomi: 'ちいさい' },
    { kanji: '石', reading: 'いし',   word: '石ころ', wordKana: '□ころ',   yomi: 'いしころ' },
    { kanji: '車', reading: 'くるま', word: '車いす', wordKana: '□いす',   yomi: 'くるまいす' },
    { kanji: '赤', reading: 'あか',   word: '赤ちゃん', wordKana: '□ちゃん', yomi: 'あかちゃん' },
    { kanji: '白', reading: 'しろ',   word: '白い',   wordKana: '□い',     yomi: 'しろい' },
    { kanji: '虫', reading: 'むし',   word: '虫歯',   wordKana: '□ば',     yomi: 'むしば' },
    { kanji: '年', reading: 'ねん',   word: '一年生', wordKana: 'いち□せい', yomi: 'いちねんせい' },
    { kanji: '先', reading: 'さき',   word: '先っぽ', wordKana: '□っぽ',   yomi: 'さきっぽ' },
    { kanji: '学', reading: 'がく',   word: '学年',   wordKana: '□ねん',   yomi: 'がくねん' },
    { kanji: '校', reading: 'こう',   word: '学校',   wordKana: 'がっ□',   yomi: 'がっこう' },
    { kanji: '生', reading: 'せい',   word: '先生',   wordKana: 'せん□',   yomi: 'せんせい' },
    { kanji: '百', reading: 'ひゃく', word: '百円',   wordKana: '□えん',   yomi: 'ひゃくえん' },
    { kanji: '千', reading: 'せん',   word: '千円',   wordKana: '□えん',   yomi: 'せんえん' },
    // 追加分（1年生で習う漢字）
    { kanji: '青', reading: 'あお', word: '青空', yomi: 'あおぞら' },
    { kanji: '森', reading: 'もり', word: '森の中', yomi: 'もりのなか' },
    { kanji: '竹', reading: 'たけ', word: '竹馬', yomi: 'たけうま' },
    { kanji: '糸', reading: 'いと', word: '糸巻き', yomi: 'いとまき' },
    { kanji: '玉', reading: 'たま', word: '玉ねぎ', yomi: 'たまねぎ' },
    { kanji: '貝', reading: 'かい', word: '貝がら', yomi: 'かいがら' },
    { kanji: '王', reading: 'おう', word: '王さま', yomi: 'おうさま' },
    { kanji: '子', reading: 'こ', word: '子ねこ', yomi: 'こねこ' },
    { kanji: '男', reading: 'おとこ', word: '男の子', yomi: 'おとこのこ' },
    { kanji: '女', reading: 'おんな', word: '女の子', yomi: 'おんなのこ' },
    { kanji: '力', reading: 'ちから', word: '力持ち', yomi: 'ちからもち' },
    { kanji: '立', reading: 'た', word: '立つ', yomi: 'たつ' },
    { kanji: '出', reading: 'で', word: '出口', yomi: 'でぐち' },
    { kanji: '入', reading: 'はい', word: '入る', yomi: 'はいる' },
    { kanji: '見', reading: 'み', word: '見る', yomi: 'みる' },
    { kanji: '音', reading: 'おと', word: '物音', yomi: 'ものおと' },
    { kanji: '町', reading: 'まち', word: '町角', yomi: 'まちかど' },
    { kanji: '村', reading: 'むら', word: '村祭り', yomi: 'むらまつり' },
    { kanji: '正', reading: 'ただ', word: '正しい', yomi: 'ただしい' },
    { kanji: '夕', reading: 'ゆう', word: '夕方', yomi: 'ゆうがた' },
    { kanji: '気', reading: 'き', word: '元気', yomi: 'げんき' },
    { kanji: '休', reading: 'やす', word: '休む', yomi: 'やすむ' },
    { kanji: '金', reading: 'きん', word: '金魚', yomi: 'きんぎょ' },
    { kanji: '円', reading: 'えん', word: '百円', yomi: 'ひゃくえん' },
    { kanji: '本', reading: 'ほん', word: '本屋', yomi: 'ほんや' },
    { kanji: '文', reading: 'ぶん', word: '作文', yomi: 'さくぶん' },
    { kanji: '字', reading: 'じ', word: '文字', yomi: 'もじ' },
    { kanji: '名', reading: 'な', word: '名前', yomi: 'なまえ' },
    { kanji: '早', reading: 'はや', word: '早い', yomi: 'はやい' }
  ],
  3: [
    { kanji: '運', reading: 'うん', word: '運動会' },
    { kanji: '泳', reading: 'えい', word: '水泳' },
    { kanji: '駅', reading: 'えき', word: '駅前' },
    { kanji: '安', reading: 'やす', word: '安い' },
    { kanji: '荷', reading: 'に', word: '荷物' },
    { kanji: '階', reading: 'かい', word: '三階' },
    { kanji: '寒', reading: 'さむ', word: '寒い' },
    { kanji: '感', reading: 'かん', word: '感想' },
    { kanji: '漢', reading: 'かん', word: '漢字' },
    { kanji: '起', reading: 'お', word: '起きる' },
    { kanji: '期', reading: 'き', word: '一学期' },
    { kanji: '客', reading: 'きゃく', word: 'お客さん' },
    { kanji: '急', reading: 'きゅう', word: '急行' },
    { kanji: '球', reading: 'きゅう', word: '野球' },
    { kanji: '去', reading: 'きょ', word: '去年' },
    { kanji: '橋', reading: 'はし', word: '橋の上' },
    { kanji: '業', reading: 'ぎょう', word: '工業' },
    { kanji: '曲', reading: 'ま', word: '曲がる' },
    { kanji: '局', reading: 'きょく', word: 'ゆうびん局' },
    { kanji: '銀', reading: 'ぎん', word: '銀行' },
    { kanji: '区', reading: 'く', word: '区役所' },
    { kanji: '苦', reading: 'く', word: '苦心' },
    { kanji: '具', reading: 'ぐ', word: '道具' },
    { kanji: '君', reading: 'くん', word: '山田君' },
    { kanji: '係', reading: 'かかり', word: '係員' },
    { kanji: '軽', reading: 'けい', word: '軽音楽' },
    { kanji: '血', reading: 'けつ', word: '出血' },
    { kanji: '決', reading: 'き', word: '決める' },
    // 追加分（3年生で習う漢字。用例は3年までに習う漢字だけ）
    { kanji: '悪', reading: 'あく', word: '悪人' },
    { kanji: '暗', reading: 'あん', word: '暗号' },
    { kanji: '医', reading: 'い', word: '医者' },
    { kanji: '育', reading: 'そだ', word: '育てる' },
    { kanji: '員', reading: 'いん', word: '会員' },
    { kanji: '院', reading: 'いん', word: '病院' },
    { kanji: '飲', reading: 'の', word: '飲む' },
    { kanji: '央', reading: 'おう', word: '中央' },
    { kanji: '横', reading: 'よこ', word: '横顔' },
    { kanji: '屋', reading: 'や', word: '本屋' },
    { kanji: '温', reading: 'おん', word: '温度' },
    { kanji: '活', reading: 'かつ', word: '生活' },
    { kanji: '研', reading: 'けん', word: '研究' },
    { kanji: '向', reading: 'む', word: '向かう' },
    { kanji: '幸', reading: 'こう', word: '幸福' },
    { kanji: '港', reading: 'みなと', word: '港町' },
    { kanji: '号', reading: 'ごう', word: '番号' },
    { kanji: '祭', reading: 'まつ', word: '祭り' },
    { kanji: '仕', reading: 'し', word: '仕事' },
    { kanji: '使', reading: 'つか', word: '使う' },
    { kanji: '始', reading: 'はじ', word: '始める' },
    { kanji: '指', reading: 'ゆび', word: '指先' },
    { kanji: '歯', reading: 'は', word: '歯みがき' },
    { kanji: '次', reading: 'つぎ', word: '次の日' },
    { kanji: '持', reading: 'も', word: '持つ' },
    { kanji: '式', reading: 'しき', word: '入学式' },
    { kanji: '実', reading: 'じつ', word: '実力' },
    { kanji: '写', reading: 'しゃ', word: '写真' },
    { kanji: '主', reading: 'しゅ', word: '主人' },
    { kanji: '守', reading: 'まも', word: '守る' },
    { kanji: '取', reading: 'と', word: '取る' },
    { kanji: '受', reading: 'う', word: '受ける' },
    { kanji: '州', reading: 'しゅう', word: '九州' },
    { kanji: '拾', reading: 'ひろ', word: '拾う' },
    { kanji: '終', reading: 'お', word: '終わる' },
    { kanji: '習', reading: 'なら', word: '習う' },
    { kanji: '集', reading: 'あつ', word: '集める' },
    { kanji: '住', reading: 'す', word: '住む' },
    { kanji: '重', reading: 'おも', word: '重い' },
    { kanji: '宿', reading: 'しゅく', word: '宿題' },
    { kanji: '所', reading: 'しょ', word: '場所' },
    { kanji: '暑', reading: 'あつ', word: '暑い' },
    { kanji: '助', reading: 'たす', word: '助ける' },
    { kanji: '昭', reading: 'しょう', word: '昭和' },
    { kanji: '消', reading: 'け', word: '消す' },
    { kanji: '商', reading: 'しょう', word: '商店' },
    { kanji: '勝', reading: 'か', word: '勝つ' },
    { kanji: '乗', reading: 'の', word: '乗る' },
    { kanji: '植', reading: 'う', word: '植える' },
    { kanji: '身', reading: 'しん', word: '全身' },
    { kanji: '神', reading: 'かみ', word: '神様' },
    { kanji: '深', reading: 'ふか', word: '深い' },
    { kanji: '進', reading: 'すす', word: '進む' },
    { kanji: '世', reading: 'せ', word: '世界' },
    { kanji: '相', reading: 'そう', word: '相談' },
    { kanji: '速', reading: 'はや', word: '速い' },
    { kanji: '族', reading: 'ぞく', word: '家族' },
    { kanji: '対', reading: 'たい', word: '対話' },
    { kanji: '反', reading: 'はん', word: '反対' },
    { kanji: '代', reading: 'だい', word: '時代' },
    { kanji: '題', reading: 'だい', word: '話題' },
    { kanji: '炭', reading: 'たん', word: '石炭' },
    { kanji: '短', reading: 'みじか', word: '短い' },
    { kanji: '着', reading: 'き', word: '着る' },
    { kanji: '注', reading: 'ちゅう', word: '注意' },
    { kanji: '帳', reading: 'ちょう', word: '手帳' },
    { kanji: '調', reading: 'しら', word: '調べる' },
    { kanji: '庭', reading: 'にわ', word: '庭先' },
    { kanji: '鉄', reading: 'てつ', word: '鉄道' },
    { kanji: '転', reading: 'てん', word: '回転' },
    { kanji: '度', reading: 'ど', word: '角度' },
    { kanji: '投', reading: 'な', word: '投げる' },
    { kanji: '豆', reading: 'まめ', word: '豆まき' },
    { kanji: '湯', reading: 'ゆ', word: '湯気' },
    { kanji: '登', reading: 'のぼ', word: '登る' },
    { kanji: '動', reading: 'うご', word: '動く' },
    { kanji: '農', reading: 'のう', word: '農家' },
    { kanji: '波', reading: 'なみ', word: '大波' },
    { kanji: '配', reading: 'くば', word: '配る' },
    { kanji: '倍', reading: 'ばい', word: '二倍' },
    { kanji: '坂', reading: 'さか', word: '坂道' },
    { kanji: '悲', reading: 'かな', word: '悲しい' },
    { kanji: '美', reading: 'うつく', word: '美しい' },
    { kanji: '鼻', reading: 'はな', word: '鼻水' },
    { kanji: '氷', reading: 'こおり', word: '氷水' },
    { kanji: '秒', reading: 'びょう', word: '一秒' },
    { kanji: '病', reading: 'びょう', word: '病気' },
    { kanji: '品', reading: 'しな', word: '品物' },
    { kanji: '部', reading: 'ぶ', word: '全部' },
    { kanji: '服', reading: 'ふく', word: '和服' },
    { kanji: '洋', reading: 'よう', word: '洋食' },
    { kanji: '物', reading: 'もの', word: '買い物' },
    { kanji: '返', reading: 'かえ', word: '返す' },
    { kanji: '勉', reading: 'べん', word: '勉強' },
    { kanji: '味', reading: 'あじ', word: '味見' },
    { kanji: '面', reading: 'めん', word: '地面' },
    { kanji: '役', reading: 'やく', word: '役所' },
    { kanji: '薬', reading: 'くすり', word: '薬屋' },
    { kanji: '油', reading: 'あぶら', word: '油絵' },
    { kanji: '有', reading: 'ゆう', word: '有名' },
    { kanji: '遊', reading: 'あそ', word: '遊ぶ' },
    { kanji: '予', reading: 'よ', word: '予定' },
    { kanji: '葉', reading: 'は', word: '葉っぱ' },
    { kanji: '陽', reading: 'よう', word: '太陽' },
    { kanji: '落', reading: 'お', word: '落ちる' },
    { kanji: '流', reading: 'なが', word: '流れる' },
    { kanji: '旅', reading: 'たび', word: '旅人' },
    { kanji: '両', reading: 'りょう', word: '両手' },
    { kanji: '緑', reading: 'みどり', word: '緑色' },
    { kanji: '礼', reading: 'れい', word: 'お礼' },
    { kanji: '列', reading: 'れつ', word: '行列' },
    { kanji: '練', reading: 'れん', word: '練習' },
    { kanji: '路', reading: 'ろ', word: '道路' },
    { kanji: '和', reading: 'わ', word: '平和' }
  ],
  5: [
    { kanji: '圧', reading: 'あつ', word: '圧力' },
    { kanji: '易', reading: 'い', word: '容易' },
    { kanji: '移', reading: 'うつ', word: '移る' },
    { kanji: '因', reading: 'いん', word: '原因' },
    { kanji: '永', reading: 'えい', word: '永遠' },
    { kanji: '営', reading: 'えい', word: '営業' },
    { kanji: '衛', reading: 'えい', word: '衛星' },
    { kanji: '益', reading: 'えき', word: '利益' },
    { kanji: '液', reading: 'えき', word: '液体' },
    { kanji: '演', reading: 'えん', word: '演技' },
    { kanji: '往', reading: 'おう', word: '往復' },
    { kanji: '桜', reading: 'さくら', word: '桜の花' },
    { kanji: '可', reading: 'か', word: '可能' },
    { kanji: '仮', reading: 'かり', word: '仮の話' },
    { kanji: '価', reading: 'か', word: '価格' },
    { kanji: '河', reading: 'か', word: '河口' },
    { kanji: '過', reading: 'す', word: '過ごす' },
    { kanji: '快', reading: 'かい', word: '快晴' },
    { kanji: '解', reading: 'かい', word: '理解' },
    { kanji: '格', reading: 'かく', word: '合格' },
    { kanji: '確', reading: 'かく', word: '確実' },
    { kanji: '額', reading: 'がく', word: '金額' },
    { kanji: '刊', reading: 'かん', word: '夕刊' },
    { kanji: '幹', reading: 'みき', word: '木の幹' },
    { kanji: '基', reading: 'き', word: '基本' },
    { kanji: '寄', reading: 'き', word: '寄付' },
    { kanji: '規', reading: 'き', word: '規則' },
    // 追加分（5年生で習う漢字。用例は5年までに習う漢字だけ）
    { kanji: '応', reading: 'おう', word: '応答' },
    { kanji: '賀', reading: 'が', word: '年賀' },
    { kanji: '慣', reading: 'な', word: '慣れる' },
    { kanji: '眼', reading: 'がん', word: '眼科' },
    { kanji: '技', reading: 'ぎ', word: '技術' },
    { kanji: '義', reading: 'ぎ', word: '正義' },
    { kanji: '逆', reading: 'ぎゃく', word: '逆転' },
    { kanji: '久', reading: 'ひさ', word: '久しぶり' },
    { kanji: '旧', reading: 'きゅう', word: '新旧' },
    { kanji: '居', reading: 'い', word: '居間' },
    { kanji: '許', reading: 'きょ', word: '許可' },
    { kanji: '境', reading: 'きょう', word: '国境' },
    { kanji: '均', reading: 'きん', word: '平均' },
    { kanji: '禁', reading: 'きん', word: '禁止' },
    { kanji: '句', reading: 'く', word: '文句' },
    { kanji: '群', reading: 'む', word: '群れ' },
    { kanji: '経', reading: 'けい', word: '経験' },
    { kanji: '潔', reading: 'けつ', word: '清潔' },
    { kanji: '件', reading: 'けん', word: '事件' },
    { kanji: '険', reading: 'けん', word: '保険' },
    { kanji: '検', reading: 'けん', word: '検査' },
    { kanji: '限', reading: 'かぎ', word: '限る' },
    { kanji: '現', reading: 'げん', word: '現在' },
    { kanji: '減', reading: 'へ', word: '減る' },
    { kanji: '故', reading: 'こ', word: '事故' },
    { kanji: '個', reading: 'こ', word: '個人' },
    { kanji: '効', reading: 'こう', word: '効果' },
    { kanji: '厚', reading: 'あつ', word: '厚い' },
    { kanji: '耕', reading: 'たがや', word: '耕す' },
    { kanji: '航', reading: 'こう', word: '航海' },
    { kanji: '鉱', reading: 'こう', word: '鉱山' },
    { kanji: '構', reading: 'かま', word: '構える' },
    { kanji: '興', reading: 'きょう', word: '興味' },
    { kanji: '講', reading: 'こう', word: '講堂' },
    { kanji: '告', reading: 'つ', word: '告げる' },
    { kanji: '混', reading: 'こん', word: '混雑' },
    { kanji: '査', reading: 'さ', word: '調査' },
    { kanji: '再', reading: 'さい', word: '再会' },
    { kanji: '災', reading: 'さい', word: '火災' },
    { kanji: '採', reading: 'と', word: '採る' },
    { kanji: '際', reading: 'さい', word: '国際' },
    { kanji: '在', reading: 'ざい', word: '在学' },
    { kanji: '財', reading: 'ざい', word: '財産' },
    { kanji: '酸', reading: 'さん', word: '酸性' },
    { kanji: '賛', reading: 'さん', word: '賛成' },
    { kanji: '支', reading: 'ささ', word: '支える' },
    { kanji: '枝', reading: 'えだ', word: '小枝' },
    { kanji: '師', reading: 'し', word: '医師' },
    { kanji: '資', reading: 'し', word: '資料' },
    { kanji: '飼', reading: 'か', word: '飼う' },
    { kanji: '示', reading: 'しめ', word: '示す' },
    { kanji: '似', reading: 'に', word: '似る' },
    { kanji: '識', reading: 'しき', word: '知識' },
    { kanji: '質', reading: 'しつ', word: '質問' },
    { kanji: '舎', reading: 'しゃ', word: '校舎' },
    { kanji: '謝', reading: 'あやま', word: '謝る' },
    { kanji: '授', reading: 'じゅ', word: '授業' },
    { kanji: '述', reading: 'の', word: '述べる' },
    { kanji: '術', reading: 'じゅつ', word: '手術' },
    { kanji: '準', reading: 'じゅん', word: '準備' },
    { kanji: '序', reading: 'じょ', word: '順序' },
    { kanji: '招', reading: 'まね', word: '招く' },
    { kanji: '証', reading: 'しょう', word: '証明' },
    { kanji: '象', reading: 'しょう', word: '気象' },
    { kanji: '賞', reading: 'しょう', word: '入賞' },
    { kanji: '条', reading: 'じょう', word: '条件' },
    { kanji: '状', reading: 'じょう', word: '年賀状' },
    { kanji: '常', reading: 'じょう', word: '日常' },
    { kanji: '情', reading: 'じょう', word: '感情' },
    { kanji: '織', reading: 'お', word: '織る' },
    { kanji: '職', reading: 'しょく', word: '職人' },
    { kanji: '制', reading: 'せい', word: '制服' },
    { kanji: '性', reading: 'せい', word: '性格' },
    { kanji: '政', reading: 'せい', word: '政治' },
    { kanji: '精', reading: 'せい', word: '精神' },
    { kanji: '製', reading: 'せい', word: '製品' },
    { kanji: '税', reading: 'ぜい', word: '税金' },
    { kanji: '責', reading: 'せき', word: '責任' },
    { kanji: '績', reading: 'せき', word: '成績' },
    { kanji: '絶', reading: 'た', word: '絶える' },
    { kanji: '祖', reading: 'そ', word: '祖父' },
    { kanji: '素', reading: 'そ', word: '素材' },
    { kanji: '総', reading: 'そう', word: '総理' },
    { kanji: '造', reading: 'つく', word: '造る' },
    { kanji: '像', reading: 'ぞう', word: '銅像' },
    { kanji: '増', reading: 'ふ', word: '増える' },
    { kanji: '則', reading: 'そく', word: '規則' },
    { kanji: '測', reading: 'はか', word: '測る' },
    { kanji: '属', reading: 'ぞく', word: '所属' },
    { kanji: '率', reading: 'りつ', word: '確率' },
    { kanji: '損', reading: 'そん', word: '損失' },
    { kanji: '貸', reading: 'か', word: '貸す' },
    { kanji: '態', reading: 'たい', word: '態度' },
    { kanji: '団', reading: 'だん', word: '団体' },
    { kanji: '断', reading: 'ことわ', word: '断る' },
    { kanji: '築', reading: 'きず', word: '築く' },
    { kanji: '貯', reading: 'ちょ', word: '貯金' },
    { kanji: '張', reading: 'は', word: '張る' },
    { kanji: '停', reading: 'てい', word: '停止' },
    { kanji: '適', reading: 'てき', word: '適当' },
    { kanji: '統', reading: 'とう', word: '統一' },
    { kanji: '堂', reading: 'どう', word: '食堂' },
    { kanji: '銅', reading: 'どう', word: '銅貨' },
    { kanji: '導', reading: 'みちび', word: '導く' },
    { kanji: '得', reading: 'とく', word: '得意' },
    { kanji: '毒', reading: 'どく', word: '消毒' },
    { kanji: '任', reading: 'まか', word: '任せる' },
    { kanji: '燃', reading: 'も', word: '燃える' },
    { kanji: '能', reading: 'のう', word: '能力' },
    { kanji: '破', reading: 'やぶ', word: '破る' },
    { kanji: '判', reading: 'はん', word: '判断' },
    { kanji: '比', reading: 'くら', word: '比べる' },
    { kanji: '非', reading: 'ひ', word: '非常' },
    { kanji: '費', reading: 'ひ', word: '費用' },
    { kanji: '備', reading: 'そな', word: '備える' },
    { kanji: '評', reading: 'ひょう', word: '評判' },
    { kanji: '貧', reading: 'まず', word: '貧しい' },
    { kanji: '布', reading: 'ふ', word: '毛布' },
    { kanji: '婦', reading: 'ふ', word: '夫婦' },
    { kanji: '富', reading: 'と', word: '富む' },
    { kanji: '武', reading: 'ぶ', word: '武器' },
    { kanji: '復', reading: 'ふく', word: '復習' },
    { kanji: '編', reading: 'あ', word: '編む' },
    { kanji: '弁', reading: 'べん', word: '弁当' },
    { kanji: '保', reading: 'たも', word: '保つ' },
    { kanji: '報', reading: 'ほう', word: '予報' },
    { kanji: '豊', reading: 'ゆた', word: '豊か' },
    { kanji: '防', reading: 'ふせ', word: '防ぐ' },
    { kanji: '貿', reading: 'ぼう', word: '貿易' },
    { kanji: '暴', reading: 'あば', word: '暴れる' },
    { kanji: '夢', reading: 'ゆめ', word: '正夢' },
    { kanji: '迷', reading: 'まよ', word: '迷う' },
    { kanji: '綿', reading: 'めん', word: '綿花' },
    { kanji: '輸', reading: 'ゆ', word: '輸入' },
    { kanji: '余', reading: 'あま', word: '余る' },
    { kanji: '容', reading: 'よう', word: '内容' },
    { kanji: '略', reading: 'りゃく', word: '省略' },
    { kanji: '留', reading: 'る', word: '留守' },
    { kanji: '領', reading: 'りょう', word: '領土' }
  ],
  7: [
    { kanji: '詩', reading: 'し', word: '詩集' },
    { kanji: '訪', reading: 'ほう', word: '訪問' },
    { kanji: '脈', reading: 'みゃく', word: '山脈' },
    { kanji: '普', reading: 'ふ', word: '普通' },
    { kanji: '互', reading: 'ご', word: '相互' },
    { kanji: '奮', reading: 'ふん', word: '興奮' },
    { kanji: '域', reading: 'いき', word: '地域' },
    { kanji: '継', reading: 'けい', word: '継続' },
    { kanji: '縮', reading: 'しゅく', word: '縮小' },
    { kanji: '担', reading: 'たん', word: '担当' },
    { kanji: '伏', reading: 'ふく', word: '起伏' },
    { kanji: '程', reading: 'てい', word: '過程' },
    { kanji: '沿', reading: 'えん', word: '沿岸' },
    { kanji: '革', reading: 'かく', word: '改革' },
    { kanji: '鋭', reading: 'えい', word: '鋭利' },
    { kanji: '純', reading: 'じゅん', word: '純粋' },
    { kanji: '貨', reading: 'か', word: '貨物' },
    { kanji: '鮮', reading: 'せん', word: '新鮮' },
    { kanji: '詳', reading: 'しょう', word: '詳細' },
    { kanji: '婚', reading: 'こん', word: '結婚' },
    { kanji: '訳', reading: 'やく', word: '翻訳' },
    { kanji: '載', reading: 'さい', word: '記載' },
    { kanji: '較', reading: 'かく', word: '比較' },
    { kanji: '慎', reading: 'しん', word: '慎重' },
    { kanji: '層', reading: 'そう', word: '地層' },
    // 追加分（中学で習う漢字）
    { kanji: '影', reading: 'えい', word: '影響' },
    { kanji: '概', reading: 'がい', word: '概要' },
    { kanji: '拡', reading: 'かく', word: '拡大' },
    { kanji: '該', reading: 'がい', word: '該当' },
    { kanji: '郷', reading: 'きょう', word: '故郷' },
    { kanji: '刺', reading: 'し', word: '刺激' },
    { kanji: '衝', reading: 'しょう', word: '衝突' },
    { kanji: '触', reading: 'ふ', word: '触れる' },
    { kanji: '帯', reading: 'たい', word: '熱帯' },
    { kanji: '腕', reading: 'うで', word: '腕前' },
    { kanji: '鎖', reading: 'さ', word: '鎖国' },
    { kanji: '弾', reading: 'だん', word: '弾力' },
    { kanji: '越', reading: 'こ', word: '越える' },
    { kanji: '緩', reading: 'かん', word: '緩和' },
    { kanji: '抑', reading: 'よく', word: '抑制' },
    { kanji: '抽', reading: 'ちゅう', word: '抽象' },
    { kanji: '即', reading: 'そく', word: '即座' },
    { kanji: '揮', reading: 'き', word: '発揮' },
    { kanji: '欧', reading: 'おう', word: '欧州' },
    { kanji: '紛', reading: 'ふん', word: '紛失' },
    { kanji: '磁', reading: 'じ', word: '磁石' },
    { kanji: '菌', reading: 'きん', word: '細菌' },
    { kanji: '況', reading: 'きょう', word: '状況' },
    { kanji: '沈', reading: 'しず', word: '沈む' },
    { kanji: '酵', reading: 'こう', word: '発酵' },
    { kanji: '傾', reading: 'かたむ', word: '傾く' },
    { kanji: '劇', reading: 'げき', word: '劇場' },
    { kanji: '郊', reading: 'こう', word: '郊外' },
    { kanji: '憲', reading: 'けん', word: '憲法' },
    { kanji: '乾', reading: 'かわ', word: '乾く' },
    { kanji: '湿', reading: 'しつ', word: '湿度' },
    { kanji: '宣', reading: 'せん', word: '宣言' },
    { kanji: '蓄', reading: 'ちく', word: '貯蓄' },
    { kanji: '滑', reading: 'すべ', word: '滑る' },
    { kanji: '勧', reading: 'すす', word: '勧める' },
    { kanji: '魅', reading: 'み', word: '魅力' },
    // 6年配当の漢字（小学校ではまだ習わない／中学のはじめに復習する漢字）
    { kanji: '恩', reading: 'おん', word: '恩人' },
    { kanji: '券', reading: 'けん', word: '入場券' },
    { kanji: '舌', reading: 'した', word: '舌打ち' },
    { kanji: '銭', reading: 'せん', word: '銭湯' }
  ]
};

function generateKanjiProblem(grade, diff = 1) {
  const list = KANJI_DATA[grade] || KANJI_DATA[1];
  const half = Math.ceil(list.length / 2);
  const pool = diff === 0 ? list.slice(0, half) :
               diff === 2 ? list.slice(list.length - half) :
               list;
  const correct = pool[randInt(0, pool.length - 1)];

  // ===== 1年生：選択肢を漢字で答える形式 =====
  if (grade === 1) {
    // diff 0（やさしい）だけ選択肢にふりがなを付ける。ふつう以上は漢字だけにして、
    // 「かな照合で当てる（答えの露出）」のを防ぐ。問題文の読みは全難易度で表示する。
    const showKana = diff === 0;
    const fmt = (item) => showKana ? `${item.kanji} ${item.reading}` : item.kanji;
    const correctChoice = fmt(correct);

    // 読みが同じ・読みの出だしが同じ漢字は選択肢に混ぜない（日と火、日と人（ひ／ひと）、手と天（て／てん）など）。
    const distractorPool = shuffleArray(
      list.filter(item => item.kanji !== correct.kanji &&
        !item.reading.startsWith(correct.reading) && !correct.reading.startsWith(item.reading))
    );
    const distractors = [];
    const usedKanji = new Set([correct.kanji]);
    for (const item of distractorPool) {
      if (distractors.length >= 3) break;
      if (usedKanji.has(item.kanji)) continue;
      usedKanji.add(item.kanji);
      distractors.push(fmt(item));
    }
    const choices = shuffleArray([correctChoice, ...distractors]);

    // 「ひだりて」の「ひだり」を かんじで かくと？ （□＋ひらがなの形はやめて、読みで聞く）
    const question = `「${correct.yomi}」の「${correct.reading}」を
かんじで かくと どれ？`;

    const result = {
      question,
      type: 'choice',
      choices,
      answer: correctChoice,
      key: correct.kanji,
      unitLabel: `漢字「${correct.kanji}」`
    };
    if (showKana) result.choiceFormat = 'kanji-kana'; // ふりがな付きのときだけ漢字＋かな表示
    return result;
  }

  // ===== 3年生以上：従来の形式 =====
  const askReading = Math.random() < 0.5;

  if (askReading) {
    const distractorPool = shuffleArray(list.filter(item => item.reading !== correct.reading));
    const distractors = [];
    const usedReadings = new Set([correct.reading]);
    for (const item of distractorPool) {
      if (distractors.length >= 3) break;
      if (usedReadings.has(item.reading)) continue;
      usedReadings.add(item.reading);
      distractors.push(item.reading);
    }
    while (distractors.length < 3) {
      distractors.push(correct.reading + 'ー');
    }

    const choices = shuffleArray([correct.reading, ...distractors]);

    return {
      question: `「${correct.word}」の\n「${correct.kanji}」の よみかたは？`,
      type: 'choice',
      choices,
      answer: correct.reading,
      key: correct.kanji,
      unitLabel: `漢字「${correct.kanji}」`
    };
  }

  const distractorPool = shuffleArray(list.filter(item => item.kanji !== correct.kanji && item.reading !== correct.reading && !correct.word.includes(item.kanji)));
  const distractors = [];
  const usedKanji = new Set([correct.kanji]);
  for (const item of distractorPool) {
    if (distractors.length >= 3) break;
    if (usedKanji.has(item.kanji)) continue;
    usedKanji.add(item.kanji);
    distractors.push(item.kanji);
  }
  while (distractors.length < 3) {
    distractors.push(correct.kanji);
  }

  const choices = shuffleArray([correct.kanji, ...distractors]);
  const maskedWord = correct.word.replace(correct.kanji, '□');

  return {
    question: `「${maskedWord}」の「${correct.reading}」に\nあてはまる漢字は？`,
    type: 'choice',
    choices,
    answer: correct.kanji,
    key: correct.kanji,
    unitLabel: `漢字「${correct.kanji}」`
  };
}

function shuffleArray(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// ===== こくご：ことわざ・慣用句・四字熟語クイズ =====

// read = 読み問題用。full:完全なことわざ, t:読みを問う漢字, y:正しい読み, d:まぎらわしい読み3つ。
// d には t の別の読みを絶対に入れない（答えが2つにならないように）。
const KOTOWAZA_DATA = {
  3: [
    // やさしい前半（有名なことわざ・穴埋め）
    { q: '「花より（　）」の（　）に入る言葉は？', choices: ['まんじゅう', 'だんご', 'みかん', 'おかし'], a: 'だんご', read: { full: '花よりだんご', t: '花', y: 'はな', d: ['つき', 'ゆき', 'くさ'] } },
    { q: '「七転び（　）起き」の（　）に入る数字は？', choices: ['六', '七', '八', '九'], a: '八', read: { full: '七転び八起き', t: '七', y: 'なな', d: ['ここの', 'やっ', 'むい'] } },
    { q: '「石の上にも（　）年」の（　）は？', choices: ['一', '三', '五', '十'], a: '三', read: { full: '石の上にも三年', t: '石', y: 'いし', d: ['つち', 'すな', 'みず'] } },
    { q: '「早起きは三文の（　）」の（　）は？', choices: ['そん', 'とく', 'いみ', 'かね'], a: 'とく', read: { full: '早起きは三文のとく', t: '早', y: 'はや', d: ['おそ', 'あさ', 'よる'] } },
    { q: '「（　）も木から落ちる」の（　）に入る動物は？', choices: ['ねこ', 'とり', 'さる', 'いぬ'], a: 'さる', read: { full: 'さるも木から落ちる', t: '木', y: 'き', d: ['は', 'ね', 'えだ'] } },
    { q: '「ちりもつもれば（　）となる」の（　）は？', choices: ['かわ', 'やま', 'うみ', 'そら'], a: 'やま', read: { full: 'ちりもつもれば山となる', t: '山', y: 'やま', d: ['かわ', 'たに', 'うみ'] } },
    { q: '「時は（　）なり」の（　）は？', choices: ['いし', 'かね', 'やま', 'かわ'], a: 'かね', read: { full: '時は金なり', t: '金', y: 'かね', d: ['いし', 'つち', 'みず'] } },
    { q: '「わらう門には（　）来たる」の（　）は？', choices: ['ゆき', 'かぜ', 'ふく', 'おに'], a: 'ふく', read: { full: 'わらう門には福来たる', t: '福', y: 'ふく', d: ['とみ', 'さいわ', 'めぐみ'] } },
    { q: '「急がば（　）れ」の（　）は？', choices: ['はし', 'まわ', 'すす', 'とば'], a: 'まわ', read: { full: '急がば回れ', t: '急', y: 'いそ', d: ['はや', 'おそ', 'すす'] } },
    { q: '「二（　）を おう者は 一（　）を も えず」の（　）に入る動物は？', choices: ['うさぎ', 'とり', 'ねこ', 'いぬ'], a: 'うさぎ' },
    // むずかしい後半（意味を問う）
    { q: '「犬も（　）けばぼうにあたる」の（　）は？', choices: ['は', 'ね', 'ある', 'お'], a: 'ある', read: { full: '犬も歩けばぼうに当たる', t: '犬', y: 'いぬ', d: ['ねこ', 'うし', 'とり'] } },
    { q: '「百聞は一（　）にしかず」の（　）は？', choices: ['もん', 'けん', 'ねん', 'さつ'], a: 'けん', read: { full: '百聞は一見にしかず', t: '百', y: 'ひゃく', d: ['せん', 'まん', 'じゅう'] } },
    { q: '「かえるの子はかえる」の意味は？', choices: ['子どもは親ににる', 'かえるは水がすき', '子どもは元気だ', 'かえるは小さい'], a: '子どもは親ににる', read: { full: 'かえるの子はかえる', t: '子', y: 'こ', d: ['て', 'め', 'き'] } },
    { q: '「いし橋をたたいてわたる」の意味は？', choices: ['いしの橋をこわす', 'しんちょうにものごとを行う', '橋をなんどもわたる', 'いそいでわたる'], a: 'しんちょうにものごとを行う', read: { full: 'いし橋をたたいてわたる', t: '橋', y: 'はし', d: ['みち', 'いし', 'かわ'] } },
    { q: '「のどもとすぎれば（　）をわすれる」の（　）は？', choices: ['あつさ', 'さむさ', 'いたさ', 'つらさ'], a: 'あつさ' },
    { q: '「三人よれば（　）のちえ」の（　）は？', choices: ['もんじゅ', 'おおかみ', 'ほとけ', 'ねこ'], a: 'もんじゅ' },
    { q: '「ねこに（　）」の（　）は？', choices: ['こばん', 'かね', 'たから', 'いし'], a: 'こばん' },
    { q: '「立つ鳥あとをにごさず」の意味は？', choices: ['出ていくとき、あとをきれいにする', '鳥はきれいずきだ', 'とても早く出ていく', 'あとからついていく'], a: '出ていくとき、あとをきれいにする' },
    { q: '「しっぱいはせいこうの（　）」の（　）は？', choices: ['もと', 'かぎ', 'てき', 'じゃま'], a: 'もと' },
    { q: '「かわいい子には旅をさせよ」の意味は？', choices: ['子どもには、つらいけいけんもさせたほうがよい', '子どもを旅行につれていってあげよう', '子どもにはお金をたくさんあげるのがよい', '子どもは家から出さないほうがよい'], a: '子どもには、つらいけいけんもさせたほうがよい', read: { full: 'かわいい子には旅をさせよ', t: '旅', y: 'たび', d: ['ふね', 'みち', 'うみ'] } },
    { q: '「千里の道も（　）から」の（　）は？', choices: ['一歩', '一日', 'ひとり', '一年'], a: '一歩', read: { full: '千里の道も一歩から', t: '道', y: 'みち', d: ['いえ', 'はし', 'かわ'] } },
    { q: '「かっぱの川ながれ」の意味は？', choices: ['その道の名人でも、しっぱいすることがある', 'かっぱはおよぎが下手で、川でおぼれる', '川の流れはいつも速くてあぶない', '水の中で長い時間すごすことができる'], a: 'その道の名人でも、しっぱいすることがある' },
    { q: '「とらぬ（　）の皮算用」の（　）は？', choices: ['たぬき', 'きつね', 'うさぎ', 'さる'], a: 'たぬき' },
    { q: '「えびで（　）をつる」の（　）は？', choices: ['たい', 'ひらめ', 'まぐろ', 'さば'], a: 'たい' },
    { q: '「負けるが勝ち」の意味は？', choices: ['ときには相手にゆずるほうが、けっきょくとくになる', 'いつもわざと負けるのがいちばんよい', '勝つことがいちばん大切で、負けてはいけない', '負けても少しもくやしくないものだ'], a: 'ときには相手にゆずるほうが、けっきょくとくになる', read: { full: '負けるが勝ち', t: '勝', y: 'か', d: ['ま', 'お', 'の'] } },
  ],
  5: [
    // やさしい前半（有名な慣用句・意味を問う）
    { q: '「ねこの手も借りたい」の意味は？', choices: ['ねこがかわいくてたまらない', 'とてもいそがしくて だれの助けでも借りたい', 'ねこにお願いして手伝ってもらう', '手がよごれていて何もさわれない'], a: 'とてもいそがしくて だれの助けでも借りたい', read: { full: 'ねこの手も借りたい', t: '借', y: 'か', d: ['と', 'ぬ', 'さ'] } },
    { q: '「足をあらう」の意味は？', choices: ['足をきれいにする', '悪いことをやめる', '旅を終える', 'つかれる'], a: '悪いことをやめる', read: { full: '足をあらう', t: '足', y: 'あし', d: ['て', 'あたま', 'ゆび'] } },
    { q: '「口が軽い」の意味は？', choices: ['食べるのが速い', 'しゃべりすぎる', '口が小さい', '話すのが上手'], a: 'しゃべりすぎる', read: { full: '口が軽い', t: '軽', y: 'かる', d: ['おも', 'ふと', 'かた'] } },
    { q: '「手を貸す」の意味は？', choices: ['手をさわる', '物をわたす', '助ける', '手がとどく'], a: '助ける', read: { full: '手を貸す', t: '貸', y: 'か', d: ['かえ', 'と', 'う'] } },
    { q: '「鼻が高い」の意味は？', choices: ['鼻が大きい', 'においがわかる', '得意になる・じまんに思う', '顔が高い'], a: '得意になる・じまんに思う', read: { full: '鼻が高い', t: '鼻', y: 'はな', d: ['みみ', 'め', 'くち'] } },
    { q: '「耳がいたい」の意味は？', choices: ['耳が聞こえにくい', '耳をさわれない', '自分の弱点を言われてつらい', '耳が大きい'], a: '自分の弱点を言われてつらい', read: { full: '耳がいたい', t: '耳', y: 'みみ', d: ['め', 'はな', 'くち'] } },
    { q: '「目をつぶる」の意味は？', choices: ['ねむくなって目をとじる', 'わざと見なかったことにする', '目がわるくて、よく見えない', '目がつかれて、休みたくなる'], a: 'わざと見なかったことにする', read: { full: '目をつぶる', t: '目', y: 'め', d: ['みみ', 'はな', 'て'] } },
    { q: '「馬が合う」の意味は？', choices: ['馬に乗るのが上手', '気が合う・相性がよい', '馬と仲良し', '足が速い'], a: '気が合う・相性がよい', read: { full: '馬が合う', t: '馬', y: 'うま', d: ['うし', 'とり', 'いぬ'] } },
    // むずかしい後半（紛らわしい慣用句・ことわざ）
    { q: '「頭が上がらない」の意味は？', choices: ['せがひくくて、上を見られない', '頭が重くて、持ち上げられない', '相手に引け目があって対等に接することができない', '頭がいたくて、起き上がれない'], a: '相手に引け目があって対等に接することができない', read: { full: '頭が上がらない', t: '頭', y: 'あたま', d: ['あし', 'かた', 'こし'] } },
    { q: '「はらをわって話す」の意味は？', choices: ['おなかがいたい', '本音で話し合う', '大きな声で話す', 'たくさん食べる'], a: '本音で話し合う', read: { full: 'はらをわって話す', t: '話', y: 'はな', d: ['かた', 'い', 'よ'] } },
    { q: '「お茶をにごす」の意味は？', choices: ['お茶を作る', 'その場をごまかす', 'お茶が好き', 'きたない水を飲む'], a: 'その場をごまかす', read: { full: 'お茶をにごす', t: '茶', y: 'ちゃ', d: ['みず', 'ゆ', 'は'] } },
    { q: '「気が置けない」の意味は？', choices: ['気をつけなければならない', '気をつかわなくてよい', '気が強い', 'やる気がない'], a: '気をつかわなくてよい', read: { full: '気が置けない', t: '置', y: 'お', d: ['と', 'き', 'さ'] } },
    { q: '「雨ふって地固まる」の意味は？', choices: ['雨がふると地面が固くなる', 'もめごとの後はかえって関係が良くなる', 'つゆが好き', '雨の後は晴れる'], a: 'もめごとの後はかえって関係が良くなる', read: { full: '雨ふって地固まる', t: '固', y: 'かた', d: ['やわ', 'まる', 'ま'] } },
    { q: '「やきもちをやく」の意味は？', choices: ['もちをやく料理', 'ねたむ', 'おこる', 'やきもちを食べる'], a: 'ねたむ' },
    { q: '「情けは人のためならず」の本当の意味は？', choices: ['人に親切にしても意味がない', '人に親切にすると回り回って自分のためになる', '情けをかけてはいけない', '人にはやさしくしなくてよい'], a: '人に親切にすると回り回って自分のためになる', read: { full: '情けは人のためならず', t: '情', y: 'なさ', d: ['こころ', 'なみだ', 'おも'] } },
    { q: '「顔が広い」の意味は？', choices: ['知り合いが多い', '顔が大きい', 'よく笑う', '美人だ'], a: '知り合いが多い', read: { full: '顔が広い', t: '広', y: 'ひろ', d: ['ひら', 'はば', 'ふと'] } },
    { q: '「水に流す」の意味は？', choices: ['過ぎたことをとがめない', '水を川にすてて、きれいにする', '水泳をして、川の流れにのる', '水におぼれて、動けなくなる'], a: '過ぎたことをとがめない', read: { full: '水に流す', t: '流', y: 'なが', d: ['あら', 'はこ', 'なら'] } },
    { q: '「首をかしげる」の意味は？', choices: ['不思議に思う', '首がいたい', 'うなずく', 'おじぎをする'], a: '不思議に思う', read: { full: '首をかしげる', t: '首', y: 'くび', d: ['て', 'あし', 'かた'] } },
    { q: '「歯が立たない」の意味は？', choices: ['相手が強くて、かなわない', '歯をみがくのをわすれてしまった', '歯がぬけて、話しにくくなる', '歯のいたみで、ねむれない'], a: '相手が強くて、かなわない' },
    { q: '「ほねを折る」の意味は？', choices: ['苦労して力をつくす', 'ほねがおれる', 'けがをする', 'あきらめる'], a: '苦労して力をつくす' },
    { q: '「かたをもつ」の意味は？', choices: ['味方をする', '荷物を持つ', 'かたをたたく', 'ケンカをする'], a: '味方をする' },
    { q: '「へそを曲げる」の意味は？', choices: ['きげんをわるくする', 'おなかがいたい', '体を曲げる', 'おどる'], a: 'きげんをわるくする' },
    { q: '「油を売る」の意味は？', choices: ['仕事のとちゅうでなまける', 'あぶらを売る店を開く', 'お金をたくさんもうける', '料理にあぶらをたくさん使う'], a: '仕事のとちゅうでなまける', read: { full: '油を売る', t: '売', y: 'う', d: ['か', 'つ', 'と'] } },
    { q: '「したをまく」の意味は？', choices: ['とても感心する', 'したがいたい', '話すのがうまい', 'おいしい'], a: 'とても感心する' },
    { q: '「目がない」の意味は？', choices: ['とても好きである', '目が見えない', '目がわるい', '目をとじる'], a: 'とても好きである', read: { full: '目がない', t: '目', y: 'め', d: ['みみ', 'はな', 'くち'] } },
    { q: '「てをやく」の意味は？', choices: ['あつかいにこまる', 'ご飯をつくる', '火をつける', '手をあたためる'], a: 'あつかいにこまる' },
    { q: '「息をのむ」の意味は？', choices: ['おどろいて、息をとめる', 'ほっとして、大きく息をはく', 'ねむくなって、息がゆっくりになる', '大きく息をすいこんで、元気を出す'], a: 'おどろいて、息をとめる' },
    { q: '「顔から火が出る」の意味は？', choices: ['とてもはずかしい', 'かぜをひく', '顔があつい日', 'おこる'], a: 'とてもはずかしい', read: { full: '顔から火が出る', t: '顔', y: 'かお', d: ['かわ', 'かた', 'かみ'] } },
  ],
  7: [
    // やさしい前半（有名な四字熟語）
    { q: '「一石二鳥」の意味は？', choices: ['石を二つ投げる', '一つの行動で二つの利益を得る', '二羽の鳥を捕まえる', '一回で全部終わらせる'], a: '一つの行動で二つの利益を得る', read: { full: '一石二鳥', t: '鳥', y: 'ちょう', d: ['ぎょ', 'けい', 'じゅう'] } },
    { q: '「以心伝心」の意味は？', choices: ['手紙で気持ちを伝える', '言葉を使わなくても心が通じ合う', 'テレパシーを使う', '心から心へ伝言する'], a: '言葉を使わなくても心が通じ合う', read: { full: '以心伝心', t: '伝', y: 'でん', d: ['しん', 'い', 'き'] } },
    { q: '「温故知新」の意味は？', choices: ['古いものは、まったく知らなくてよい', '昔のことを大切にしながら新しいことを学ぶ', '新しいことだけを学べばよい', '過去のことは、どうしても変えられない'], a: '昔のことを大切にしながら新しいことを学ぶ', read: { full: '温故知新', t: '温', y: 'おん', d: ['こ', 'ち', 'しん'] } },
    { q: '「転ばぬ先の杖」の意味は？', choices: ['転んでから立つ', '事前に準備をしておく', '杖は歩くのに必要', '先に進むには勇気が必要'], a: '事前に準備をしておく', read: { full: '転ばぬ先の杖', t: '先', y: 'さき', d: ['まえ', 'あと', 'うし'] } },
    { q: '「棚からぼたもち」の意味は？', choices: ['棚の上にもちがある', '思いがけない幸運が転がり込む', 'ぼたもちは棚に置くもの', '努力せずに得をする方法'], a: '思いがけない幸運が転がり込む', read: { full: '棚からぼたもち', t: '棚', y: 'たな', d: ['はこ', 'つくえ', 'ほん'] } },
    { q: '「灯台下暗し」の意味は？', choices: ['灯台は明るい', '身近なことほど気がつきにくい', '暗い場所は危ない', '電気をつけ忘れる'], a: '身近なことほど気がつきにくい', read: { full: '灯台下暗し', t: '暗', y: 'くら', d: ['あか', 'しろ', 'くろ'] } },
    { q: '「五十歩百歩」の意味は？', choices: ['百歩の方が五十歩より二倍多い', '少しの差はあっても本質的には同じ', '歩く速さのちがい', '距離の比較'], a: '少しの差はあっても本質的には同じ', read: { full: '五十歩百歩', t: '百', y: 'ひゃく', d: ['せん', 'まん', 'じゅう'] } },
    { q: '「知らぬが仏」の意味は？', choices: ['仏は何でも知っている', '知らないことが幸せなこともある', '無知は罪だ', '仏様だけが真実を知っている'], a: '知らないことが幸せなこともある', read: { full: '知らぬが仏', t: '仏', y: 'ほとけ', d: ['かみ', 'おに', 'さま'] } },
    // むずかしい後半（やや難しい四字熟語・故事成語）
    { q: '「七転八倒」の意味は？', choices: ['七回転んで八回起き上がる', 'ひどい苦しみにもがく', '七つの困難と八つの成功', '転がり続ける'], a: 'ひどい苦しみにもがく', read: { full: '七転八倒', t: '倒', y: 'とう', d: ['てん', 'はち', 'しち'] } },
    { q: '「虎の威を借る狐」の意味は？', choices: ['狐は、虎よりもずっと強い動物だ', '権力ある者の力を借りて威張る人', '虎と狐は、とても仲がよい', '動物どうしが、たがいに協力しあう'], a: '権力ある者の力を借りて威張る人', read: { full: '虎の威を借る狐', t: '虎', y: 'とら', d: ['りゅう', 'ねこ', 'うま'] } },
    { q: '「付和雷同」の意味は？', choices: ['雷が鳴ると雨が降る', '自分の意見を持たずに他人に同調する', '友達と一緒に行動する', '大勢で協力する'], a: '自分の意見を持たずに他人に同調する', read: { full: '付和雷同', t: '雷', y: 'らい', d: ['でん', 'う', 'ふう'] } },
    { q: '「画竜点睛」の意味は？', choices: ['竜の絵を描く', '最後の仕上げで全体が生きてくる', '竜に目を描く', '完成直前で失敗する'], a: '最後の仕上げで全体が生きてくる', read: { full: '画竜点睛', t: '点', y: 'てん', d: ['が', 'りゅう', 'せい'] } },
    { q: '「臥薪嘗胆」の意味は？', choices: ['薪の上で寝て胆を舐める', '目的のために苦労に耐えて力を蓄える', '病気のときの薬', 'たいへん苦い経験'], a: '目的のために苦労に耐えて力を蓄える', read: { full: '臥薪嘗胆', t: '胆', y: 'たん', d: ['しん', 'しょう', 'が'] } },
    { q: '「羊頭狗肉」の意味は？', choices: ['羊と犬の料理', '見せかけと実態が異なる', '動物の肉の違い', '外見通りの内容である'], a: '見せかけと実態が異なる', read: { full: '羊頭狗肉', t: '羊', y: 'よう', d: ['とう', 'く', 'にく'] } },
    { q: '「杞憂」の意味は？', choices: ['杞の国の心配', '取り越し苦労・必要のない心配', '心配することは大切', '心配しすぎると疲れる'], a: '取り越し苦労・必要のない心配', read: { full: '杞憂', t: '憂', y: 'ゆう', d: ['き', 'しん', 'あん'] } },
    { q: '「十人十色」の意味は？', choices: ['人によって考え方や好みはちがう', '十人でおなじ色を好む', '十色のえのぐ', '十人でそろって行動する'], a: '人によって考え方や好みはちがう' },
    { q: '「一期一会」の意味は？', choices: ['一生に一度の出会いを大切にする', '一回でやめる', '毎日会う', '一年に一度の会合'], a: '一生に一度の出会いを大切にする' },
    { q: '「有名無実」の意味は？', choices: ['名前だけで中身がない', '有名で中身もある', '名前を変える', '無名で実力がある'], a: '名前だけで中身がない', read: { full: '有名無実', t: '実', y: 'じつ', d: ['しつ', 'じん', 'せき'] } },
    { q: '「自画自賛」の意味は？', choices: ['自分で自分をほめる', '自分の絵を売る', '人の絵をほめる', '絵をかくのがうまい'], a: '自分で自分をほめる', read: { full: '自画自賛', t: '賛', y: 'さん', d: ['しん', 'ざん', 'せん'] } },
    { q: '「大器晩成」の意味は？', choices: ['大人物は、おそくなってから成功する', '若いうちに、早く成功する', '器がとても大きくて使いやすい', '夕方になってから、晩ごはんを食べる'], a: '大人物は、おそくなってから成功する', read: { full: '大器晩成', t: '晩', y: 'ばん', d: ['まん', 'はん', 'ぱん'] } },
    { q: '「油断大敵」の意味は？', choices: ['気をゆるめると失敗のもとになる', '油をたくさん使うのが好き', '大きな敵がとつぜんおそってくる', 'すぐに機械に油をさしておく'], a: '気をゆるめると失敗のもとになる', read: { full: '油断大敵', t: '敵', y: 'てき', d: ['しき', 'へき', 'けき'] } },
    { q: '「異口同音」の意味は？', choices: ['多くの人が同じことを言う', '口がちがう', '音がちがう', '口をそろえて歌う'], a: '多くの人が同じことを言う', read: { full: '異口同音', t: '異', y: 'い', d: ['え', 'ゆ', 'ひ'] } },
    { q: '「千差万別」の意味は？', choices: ['ものごとはひとつひとつちがう', '千と万をくらべる', '差が小さい', '別々に行動する'], a: 'ものごとはひとつひとつちがう', read: { full: '千差万別', t: '別', y: 'べつ', d: ['へつ', 'ばつ', 'べい'] } },
    { q: '「呉越同舟」の意味は？', choices: ['仲の悪い者どうしが同じ場所にいる', '船に乗って、どこかへ旅行する', '仲のよい者どうしが、いっしょに旅行する', '船の名前を、みんなで決める'], a: '仲の悪い者どうしが同じ場所にいる', read: { full: '呉越同舟', t: '舟', y: 'しゅう', d: ['しゅ', 'せん', 'じゅう'] } },
    { q: '「蛇足」の意味は？', choices: ['よけいなもの', 'ヘビの足', '足が速い', '足を引っぱる'], a: 'よけいなもの' },
    { q: '「矛盾」の意味は？', choices: ['つじつまが合わないこと', '矛と盾を売る', '強い武器', '戦いの道具'], a: 'つじつまが合わないこと', read: { full: '矛盾', t: '矛', y: 'む', d: ['ぼう', 'もう', 'み'] } },
    { q: '「背水の陣」の意味は？', choices: ['あとがない覚悟でとりくむ', '水の中で戦う', '背中に水を背負う', '川に近づく'], a: 'あとがない覚悟でとりくむ', read: { full: '背水の陣', t: '陣', y: 'じん', d: ['ちん', 'てん', 'しん'] } },
    { q: '「馬耳東風」の意味は？', choices: ['人の意見を聞き流す', '馬の耳がいい', '東風がふく', '馬が耳をうごかす'], a: '人の意見を聞き流す', read: { full: '馬耳東風', t: '耳', y: 'じ', d: ['じん', 'ぎ', 'し'] } },
    { q: '「漁夫の利」の意味は？', choices: ['二人が争っている間に第三者が得をする', '漁師が魚をたくさんとってもうける', '魚が、あみいっぱいにかかる', 'みんなで協力して、漁をする'], a: '二人が争っている間に第三者が得をする', read: { full: '漁夫の利', t: '漁', y: 'ぎょ', d: ['ご', 'ぎょう', 'きょ'] } },
    { q: '「五里霧中」の意味は？', choices: ['見通しが立たず、どうしてよいか分からない', '五里（約20キロ）の道のりを歩く', '霧がふかくて、里が見えない', '霧の中で、みんなで楽しく遊ぶ'], a: '見通しが立たず、どうしてよいか分からない', read: { full: '五里霧中', t: '霧', y: 'む', d: ['ぶ', 'もう', 'み'] } },
  ]
};

// 4年・6年は、前後の学年の問題から つくる（4年＝3年の後半＋5年の前半、6年＝5年の後半＋中1の前半）
// その学年で まだ習わない漢字が 問題文や選択肢に入っているものは、のぞく
const KZ_NOT_FOR_4 = ['「手を貸す」', '「鼻が高い」', '「馬が合う」'];
const KZ_NOT_FOR_6 = ['一石二鳥', '転ばぬ先の杖', '棚からぼたもち', '五十歩百歩', '七転八倒', '虎の威', '付和雷同', '画竜点睛'];
KOTOWAZA_DATA[4] = KOTOWAZA_DATA[3].slice(12).concat(
  KOTOWAZA_DATA[5].slice(0, 8).filter(it => !KZ_NOT_FOR_4.some(w => it.q.includes(w))));
KOTOWAZA_DATA[6] = KOTOWAZA_DATA[5].slice(14).concat(
  KOTOWAZA_DATA[7].slice(0, 8).filter(it => !KZ_NOT_FOR_6.some(w => it.q.includes(w))));

function generateKotowazaProblem(grade, diff = 1) {
  const list = KOTOWAZA_DATA[grade] || KOTOWAZA_DATA[3];
  const half = Math.ceil(list.length / 2);
  const pool = diff === 0 ? list.slice(0, half) :
               diff === 2 ? list.slice(list.length - half) :
               list;
  const item = pool[randInt(0, pool.length - 1)];

  // 約半分の確率で「読み」問題を出す（形だけ覚えて読めないのを防ぐ反復練習）。
  // 例：「腹を割って話す」の「腹」は なんと よむ？ → はら
  if (item.read && Math.random() < 0.5) {
    const r = item.read;
    return {
      question: `「${r.full}」の\n「${r.t}」は なんと よむ？`,
      type: 'choice',
      choices: shuffleArray([r.y, ...r.d]),
      answer: r.y,
      key: item.q,
      unitLabel: `ことわざ：${item.q.replace(/[「」]/g, '').slice(0, 16)}`
    };
  }

  return {
    question: item.q,
    type: 'choice',
    choices: shuffleArray([...item.choices]),
    answer: item.a,
    key: item.q,
    unitLabel: `ことわざ：${item.q.replace(/[「」]/g, '').slice(0, 16)}`
  };
}
